### ISSUE TITLE
Error Installing v18

### ISSUE THREAD

**Issue by iamsubingyawali** [layershift/nodejs-php#4]
Hi, first of all, I really appreciate your work. I recently discovered this add-on, and it has saved a lot of extra works on my environment.

But I could not install v18.X. All versions below it work fine. While installing v18, I am receiving below error in my environment.

```
Loaded plugins: fastestmirror, ovl
Cleaning repos: base epel extras nodesource updates
Cleaning up list of fastest mirrors
Loaded plugins: fastestmirror, ovl
Determining fastest mirrors

base: centos.excellmedia.net
epel: mirror2.totbb.net
extras: centos.excellmedia.net
updates: centos.excellmedia.net
Resolving Dependencies
--> Running transaction check
---> Package nodejs.x86_64 2:17.9.0-1nodesource will be updated
---> Package nodejs.x86_64 2:18.4.0-1nodesource will be an update
--> Processing Dependency: libstdc++.so.6(GLIBCXX_3.4.21)(64bit) for package: 2:nodejs-18.4.0-1nodesource.x86_64
--> Processing Dependency: libc.so.6(GLIBC_2.28)(64bit) for package: 2:nodejs-18.4.0-1nodesource.x86_64
--> Processing Dependency: libm.so.6(GLIBC_2.27)(64bit) for package: 2:nodejs-18.4.0-1nodesource.x86_64
--> Processing Dependency: libstdc++.so.6(CXXABI_1.3.9)(64bit) for package: 2:nodejs-18.4.0-1nodesource.x86_64
--> Processing Dependency: libstdc++.so.6(GLIBCXX_3.4.20)(64bit) for package: 2:nodejs-18.4.0-1nodesource.x86_64
--> Finished Dependency Resolution
You could try using --skip-broken to work around the problem
You could try running: rpm -Va --nofiles --nodigest
Issue:
Can't install nodejs
```

**Comment by rauladorean** [comment]
Hi,

Thank you for your report. It looks like NodeJS 18 will not be supported on CentOS 7 due to the installed glibc version (glibc-2.17-326.el7_9.x86_64) and the minimum required is 2.28 or higher. There is no update for glibc available on CentOS 7.

The reasoning behind this move is that CentOS 7 will be [EOL](https://wiki.centos.org/About/Product) before NodeJS 18 will be [EOL](https://github.com/nodejs/release#release-schedule). More details [here](https://www.redhat.com/en/blog/welcome-nodejs-18) in "Platform support" section

In [Node's building instructions document](https://github.com/nodejs/node/blob/main/BUILDING.md#platform-list) for version 18 only RHEL 8 is mentioned.
